# Generated by Django 5.2.7 on 2025-12-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_options_alter_answerlike_options_and_more'),
        ('questions', '0002_question_fts_index'),
    ]

    operations = [
    ]
