# Generated by Django 5.2.7 on 2025-11-16 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_activity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общая активность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_answers',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего ответов'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_questions',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего вопросов'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-total_activity'], name='UserProfile_total_a_f3061a_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-total_questions'], name='UserProfile_total_q_e4dd08_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['-total_answers'], name='UserProfile_total_a_6a2064_idx'),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
